version: '3.1'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  joomladb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${DB_CONTAINER}
    restart: always
    ports:
      - ${JOOMLA_DB_PORT}:3306
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${JOOMLA_DB_PASSWORD}
      - MYSQL_DATABASE=${JOOMLA_DB_NAME}
      - MYSQL_USER=${JOOMLA_DB_USER}
      - MYSQL_PASSWORD=${JOOMLA_DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password

  php_myadmin:
    image: phpmyadmin:latest
    container_name: ${PHPMYADMIN_CONTAINER}
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_HOSTS=joomladb
      - VIRTUAL_HOST=phpmyadmin.local
    links:
      - joomladb

  joomla_cms:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JOOMLA_VERSION=${JOOMLA_VERSION}
        - PHP_VERSION=${PHP_VERSION}
    container_name: ${JOOMLA_CONTAINER}
    restart: always
    ports:
      - "${JOOMLA_PORT}:80"
    volumes:
      - ./joomla_data:/var/www/html:rw,delegated
      - ./custom_php.ini:/usr/local/etc/php/conf.d/custom_php.ini
    environment:
      - JOOMLA_SITE_NAME=${JOOMLA_SITENAME}
      - JOOMLA_ADMIN_EMAIL=${SUPERUSER_EMAIL}
      - JOOMLA_ADMIN_USERNAME=${SUPERUSER_USERNAME}
      - JOOMLA_ADMIN_USER=${SUPERUSER_NAME}
      - JOOMLA_ADMIN_PASSWORD=${SUPERUSER_PWD}
      - JOOMLA_DB_USER=${JOOMLA_DB_USER}
      - JOOMLA_DB_PASSWORD=${JOOMLA_DB_PASSWORD}
      - JOOMLA_DB_NAME=${JOOMLA_DB_NAME}
      - JOOMLA_DB_HOST=joomladb
      - JOOMLA_DB_PREFIX=${JOOMLA_DB_PREFIX}
      - VIRTUAL_HOST=${JOOMLA_VIRTUAL_HOST}
    links:
      - joomladb:mysql
    
volumes:
  mysql_db:
  joomla_data:
