version: '3.1'

services:
  joomladb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${JOOMLA_DB_HOST}
    ports:
      - "${JOOMLA_DB_PORT}:3306"
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${JOOMLA_DB_PASSWORD}
      - MYSQL_DATABASE=${JOOMLA_DB_NAME}
    command: --default-authentication-plugin=mysql_native_password

  php_myadmin:
    image: phpmyadmin:latest
    container_name: php_myadmin_joomla
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - MYSQL_ROOT_PASSWORD=${JOOMLA_DB_PASSWORD}
    links:
      - joomladb

  joomla_cms:
    image: joomla:${JOOMLA_VERSION}-php${PHP_VERSION}-apache
    container_name: joomla_cms
    ports:
      - "${JOOMLA_PORT}:80"
    volumes:
      - ./custom_php.ini:/usr/local/etc/php/conf.d/custom_php.ini:ro
      - joomla_data:/var/www/html:rw
    environment:
      - JOOMLA_DB_USER=${JOOMLA_DB_USER}
      - JOOMLA_DB_PASSWORD=${JOOMLA_DB_PASSWORD}
      - JOOMLA_DB_NAME=${JOOMLA_DB_NAME}
      - JOOMLA_DB_HOST=joomladb
    links:
      - joomladb:mysql


volumes:
  mysql_db:
  joomla_data: